Leaderboard Structure Pull Request
Solobarine/Leaderboard-Api pull request #1
Opened 2022-08-30 20:09 UTC by Solobarine

This is a pull request to review the basic structure of the Leaderboard project. Enjoy!!

2022-08-30 21:12 UTC, alexander16108 requested changes
Hi @Solobarine, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/vIzBpVFeQAvjcAfXHc/giphy.gif" style="height:50px"/>


## Required Changes ♻️
_Check the comments under the review._
- you need to add your dist folder to you GitHub repository cause its an important piece of your project 😸 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-30 21:12 UTC, alexander16108 commented on package.json
> +    "test": "webpack --config webpack.config.js"
your package file doesn't have some of the required scripts like build for this project
`"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack --config webpack.config.js --watch"
  }
`

2022-08-30 21:14 UTC, alexander16108 commented on package.json
> +    "webpack-cli": "^4.10.0"
- your package file should have a `webpack-dev-server` in your dev dependencies 👍🏾

2022-08-30 22:47 UTC, tufoinnkuo10 requested changes
Hi @Solobarine 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally


Required Changes ♻️
Check the comments under the review
- [ optional] I am putting this optional because the previous reviewer did not mention it. please use the correct git flow. you were supposed to use the dev branch as default and demand your PR into it. please look into that
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-08-30 22:47 UTC, tufoinnkuo10 commented on package.json
> +  "scripts": {
- [ ] like the previous reviewer noted, you are missing scripts like build and start, which are needed to run your app. e.g. 
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack --config webpack.config.js --watch"
  }
```

2022-08-30 22:47 UTC, tufoinnkuo10 commented on package.json
> +    "webpack-cli": "^4.10.0"
- [ ] you are still missing a dev dependency like the previous reviewer noted. `webpack-dev-server`.  please fix that

2022-08-31 00:16 UTC, mahbubul14 requested changes
Hi @Solobarine ,

Great work on making the changes requested by the previous reviewers 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

# Required Changes ♻️

- [ ] Kindly check the inline comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linter error.
:heavy_check_mark: Proper GitHub flow used.
:heavy_check_mark: Descriptive PR title.

### Optional suggestions

- [ ]  This is a mandatory requirement but I kept it optional because the previous reviewer did not mention it. Your `README` file is not descriptive. Please update your `README` file. You can use [this template ](https://github.com/microverseinc/readme-template)for the `README` but remember to customize it to your project. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-08-31 00:16 UTC, mahbubul14 commented on package.json
> +  },
- [ ]  Like the previous reviewers noted, you are missing scripts like start, which are needed to run your app. You can check the examples below to get an idea of how to write "start" scripts. There should be a way to start the project, say `npm run start`

**EX:**
```
"scripts": {
    "start": "webpack --config webpack.config.js --watch"
  }
  
  ```
  Or,
```
  "scripts": {
     "start": "webpack serve --open"
  }
```

2022-08-31 09:40 UTC, HAMMAS-SALEEM approved these changes
# Status: Approved :green_circle:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)

## Hey @Solobarine  :wave:

Great work on implementing the changes requested by the previous reviewer. Your project is complete. :blush:
There is nothing else to say about your project. :+1:

## Highlights :1st_place_medal:

:heavy_check_mark: Following the GitFlow
:heavy_check_mark: Following requirements
:heavy_check_mark: Following Webpack Documentation

# Optional


_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-31 09:40 UTC, HAMMAS-SALEEM commented on package.json
> +    "start": "webpack --config webpack.config.js",
**[Optional]**

- [ ] Please add `"start": "webpack serve --open"` instead of `"start": "webpack --config webpack.config.js"` because your project is not starting on server. If it is not starting then how are you gonna see your project working :thinking:

2022-08-31 11:35 UTC, merged